### ISSUE TITLE
Table format disorder

### ISSUE THREAD

**Issue by StevyZheng** [Adam23713/Console-Table#2]
I use ConsoleTable and same long table header, so the table display disorder,
like this:
![1](https://user-images.githubusercontent.com/12432363/43383086-824550bc-940c-11e8-93f6-2f8ce5a15a79.jpg)

**Comment by Adam23713** [comment]
Hello!
Thank you for your feedback!
I fixed it, and commited to GitHub.

Best Regards,
K.Adam

StevyZheng <notifications@github.com> ezt írta (időpont: 2018. júl. 30., H,
9:24):
